In [1]:
import pandas as pd
import sklearn
import matplotlib as plt
from pycaret.regression import *

In [2]:
df = pd.read_csv('5.extended_df.csv')
df.index = df['Unnamed: 0']
df.drop(['Unnamed: 0', 'row', 'column', 'lat_min', 'lat_max', 'lon_min', 'lon_max'], axis = 1, inplace = True)
df.drop(list(df.filter(regex = 'tourism_')),axis = 1, inplace = True)
df

,nature,entertainment,transports,art,tourism,security,accessibility,sport,nature_west,entertainment_west,...,sport_south_west,security_south_west,accessibility_south_west,nature_north_west,entertainment_north_west,transports_north_west,art_north_west,sport_north_west,security_north_west,accessibility_north_west
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
R1C1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R1C2,1.0,3.0,5.0,0.0,3.0,0.0,5.0,0.0,4.0,1.0,...,0.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0
R1C3,4.0,1.0,34.0,0.0,2.0,0.0,4.0,0.0,9.0,0.0,...,0.0,0.0,0.0,4.0,0.0,4.0,0.0,0.0,0.0,0.0
R1C4,9.0,0.0,25.0,0.0,1.0,0.0,1.0,0.0,6.0,2.0,...,0.0,0.0,0.0,4.0,2.0,11.0,0.0,0.0,0.0,0.0
R1C5,6.0,2.0,20.0,0.0,0.0,0.0,0.0,0.0,16.0,8.0,...,0.0,0.0,0.0,2.0,0.0,23.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
R200C196,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R200C197,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R200C198,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R200C199,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R200C200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
df.describe()

,nature,entertainment,transports,art,tourism,security,accessibility,sport,nature_west,entertainment_west,...,sport_south_west,security_south_west,accessibility_south_west,nature_north_west,entertainment_north_west,transports_north_west,art_north_west,sport_north_west,security_north_west,accessibility_north_west
count,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.0000,40000.000000,40000.000000,...,40000.0000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.0000,40000.000000,40000.000000
mean,14.450950,1.502125,19.839100,0.188475,0.299300,0.123500,0.577975,0.0001,14.450950,1.502125,...,0.0001,0.123500,0.577950,14.320125,1.489450,19.647675,0.187325,0.0001,0.121675,0.571950
std,34.657835,8.541670,48.065601,0.930819,2.009184,1.473194,2.599998,0.0100,34.657835,8.541670,...,0.0100,1.473194,2.599999,34.553665,8.528552,47.872590,0.929546,0.0100,1.468613,2.588888
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,...,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,...,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,1.000000,0.000000,...,0.0000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000
75%,18.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.0000,18.000000,0.000000,...,0.0000,0.000000,0.000000,18.000000,0.000000,11.000000,0.000000,0.0000,0.000000,0.000000
max,1007.000000,474.000000,845.000000,34.000000,156.000000,129.000000,79.000000,1.0000,1007.000000,474.000000,...,1.0000,129.000000,79.000000,1007.000000,474.000000,845.000000,34.000000,1.0000,129.000000,79.000000

In [4]:
exp = setup(df, target = 'tourism')

In [5]:
best = compare_models(n_select = 3)

Processing:   0%|          | 0/79 [00:00<?, ?it/s]

In [6]:
evaluate_model(best[0])

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…