In [1]:
import pandas as pd
import sklearn
import matplotlib as plt
from pycaret.regression import *

In [2]:
df = pd.read_csv('1. filtered_df.csv')
df.index = df['Unnamed: 0']
df.drop(['Unnamed: 0', 'row', 'column', 'lat_min', 'lat_max', 'lon_min', 'lon_max'], axis = 1, inplace = True)
df

,nature,entartainment,transports,art,sport,tourism,security,accessibility
Unnamed: 0,,,,,,,,
R1C36,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R1C37,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R1C38,54.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
R1C39,46.0,1.0,13.0,1.0,0.0,0.0,0.0,0.0
R1C40,17.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
R100C96,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
R100C97,17.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0
R100C98,182.0,0.0,12.0,0.0,0.0,3.0,0.0,0.0
R100C99,171.0,0.0,22.0,1.0,0.0,6.0,0.0,0.0
R100C100,3.0,0.0,5.0,0.0,0.0,3.0,0.0,0.0

In [3]:
exp = setup(df, target = 'tourism')

In [4]:
best = compare_models(n_select = 3)

Processing:   0%|          | 0/79 [00:00<?, ?it/s]

In [5]:
evaluate_model(best[0])

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦

In [6]:
tuned_model = tune_model(best[0])

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits

# Expanding the Model - Interaction Effect and Polynomial Features

In [7]:
expanded_df = df.copy()
columns = expanded_df.columns.to_list()
columns.remove('tourism')

In [8]:
for a in columns:
    for b in columns:
        expanded_df[a + ' x ' + b ] = expanded_df[a] * expanded_df[b]

In [9]:
expanded_df

,nature,entartainment,transports,art,sport,tourism,security,accessibility,nature x nature,nature x entartainment,...,security x sport,security x security,security x accessibility,accessibility x nature,accessibility x entartainment,accessibility x transports,accessibility x art,accessibility x sport,accessibility x security,accessibility x accessibility
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
R1C36,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R1C37,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R1C38,54.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,2916.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R1C39,46.0,1.0,13.0,1.0,0.0,0.0,0.0,0.0,2116.0,46.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R1C40,17.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,289.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
R100C96,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R100C97,17.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,289.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R100C98,182.0,0.0,12.0,0.0,0.0,3.0,0.0,0.0,33124.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R100C99,171.0,0.0,22.0,1.0,0.0,6.0,0.0,0.0,29241.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R100C100,3.0,0.0,5.0,0.0,0.0,3.0,0.0,0.0,9.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
exp = setup(expanded_df, target = 'tourism')

In [11]:
best_expanded = compare_models()

Processing:   0%|          | 0/77 [00:00<?, ?it/s]

In [12]:
evaluate_model(best_expanded)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦

# Ensemble Models

In [13]:
bagged = ensemble_model(best[0], method = 'Bagging')

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

In [14]:
boosting = ensemble_model(best[0], method = 'Boosting')

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

In [15]:
blender = blend_models(best)

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

In [16]:
stacking = stack_models(best)

Processing:   0%|          | 0/6 [00:00<?, ?it/s]