In [1]:
import pandas as pd
import sklearn
import matplotlib as plt
from pycaret.regression import *

In [2]:
df = pd.read_csv('5.extended_df.csv')
df.index = df['Unnamed: 0']
df.drop(['Unnamed: 0', 'row', 'column', 'lat_min', 'lat_max', 'lon_min', 'lon_max'], axis = 1, inplace = True)
df.drop(list(df.filter(regex = 'tourism_')),axis = 1, inplace = True)
df

,nature,entartainment,transports,art,sport,tourism,security,accessibility,nature_west,entartainment_west,...,sport_south_west,security_south_west,accessibility_south_west,nature_north_west,entartainment_north_west,transports_north_west,art_north_west,sport_north_west,security_north_west,accessibility_north_west
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
R1C1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
R1C2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
R1C3,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
R1C4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R1C5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
R200C196,3.0,1.0,5.0,0.0,0.0,0.0,0.0,1.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R200C197,4.0,0.0,11.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R200C198,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R200C199,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R200C200,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
df.describe()

,nature,entartainment,transports,art,sport,tourism,security,accessibility,nature_west,entartainment_west,...,sport_south_west,security_south_west,accessibility_south_west,nature_north_west,entartainment_north_west,transports_north_west,art_north_west,sport_north_west,security_north_west,accessibility_north_west
count,40000.00000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.00000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,5.68425,0.444425,9.176250,0.157775,0.259625,0.218975,0.045575,0.183050,5.68425,0.444425,...,0.259000,0.045450,0.182500,5.665825,0.444325,9.167600,0.157450,0.259425,0.045575,0.183025
std,19.32166,3.611771,24.548642,0.662830,1.316990,1.295614,0.361457,1.694185,19.32166,3.611771,...,1.316572,0.361231,1.693773,19.320370,3.611769,24.549088,0.662322,1.316821,0.361457,1.694181
min,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.00000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000
75%,5.00000,0.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.00000,0.000000,...,0.000000,0.000000,0.000000,5.000000,0.000000,7.000000,0.000000,0.000000,0.000000,0.000000
max,667.00000,302.000000,968.000000,23.000000,97.000000,74.000000,19.000000,162.000000,667.00000,302.000000,...,97.000000,19.000000,162.000000,667.000000,302.000000,968.000000,23.000000,97.000000,19.000000,162.000000

In [4]:
exp = setup(df, target = 'tourism')

In [5]:
best = compare_models(n_select = 3)

Processing:   0%|          | 0/79 [00:00<?, ?it/s]

In [7]:
evaluate_model(best[1])

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…