In [12]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib as plt
from pycaret.regression import *

In [2]:
df = pd.read_csv('5.extended_df.csv')
df.index = df['Unnamed: 0']
df.drop(['Unnamed: 0', 'row', 'column', 'lat_min', 'lat_max', 'lon_min', 'lon_max'], axis = 1, inplace = True)
df.drop(list(df.filter(regex = 'tourism_')),axis = 1, inplace = True)
df

,nature,entartainment,transports,art,sport,tourism,security,accessibility,nature_west,entartainment_west,...,sport_south_west,security_south_west,accessibility_south_west,nature_north_west,entartainment_north_west,transports_north_west,art_north_west,sport_north_west,security_north_west,accessibility_north_west
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
R1C1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
R1C2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
R1C3,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
R1C4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R1C5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
R200C196,3.0,1.0,5.0,0.0,0.0,0.0,0.0,1.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R200C197,4.0,0.0,11.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R200C198,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R200C199,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R200C200,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
df.describe()

,nature,entartainment,transports,art,sport,tourism,security,accessibility,nature_west,entartainment_west,...,sport_south_west,security_south_west,accessibility_south_west,nature_north_west,entartainment_north_west,transports_north_west,art_north_west,sport_north_west,security_north_west,accessibility_north_west
count,40000.00000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.00000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,5.68425,0.444425,9.176250,0.157775,0.259625,0.218975,0.045575,0.183050,5.68425,0.444425,...,0.259000,0.045450,0.182500,5.665825,0.444325,9.167600,0.157450,0.259425,0.045575,0.183025
std,19.32166,3.611771,24.548642,0.662830,1.316990,1.295614,0.361457,1.694185,19.32166,3.611771,...,1.316572,0.361231,1.693773,19.320370,3.611769,24.549088,0.662322,1.316821,0.361457,1.694181
min,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.00000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000
75%,5.00000,0.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.00000,0.000000,...,0.000000,0.000000,0.000000,5.000000,0.000000,7.000000,0.000000,0.000000,0.000000,0.000000
max,667.00000,302.000000,968.000000,23.000000,97.000000,74.000000,19.000000,162.000000,667.00000,302.000000,...,97.000000,19.000000,162.000000,667.000000,302.000000,968.000000,23.000000,97.000000,19.000000,162.000000

In [31]:
splits = 3
splitted_df_list = np.array_split(df, splits)

prediction_df_list = []

for splitted_df in splitted_df_list:
    training_df = df.drop(splitted_df.index)
    prediction_df = splitted_df
    
    exp = setup(training_df, target = 'tourism')
    best = compare_models()
    predictions = predict_model(best, data = prediction_df)
    
    predictions = predictions[['prediction_label']]
    predictions.index = prediction_df.index
    prediction_df_list.append(predictions)

Processing:   0%|          | 0/77 [00:00<?, ?it/s]

Processing:   0%|          | 0/77 [00:00<?, ?it/s]

Processing:   0%|          | 0/77 [00:00<?, ?it/s]

In [34]:
predictions_concat = pd.concat(prediction_df_list)

In [43]:
export_df = pd.read_csv('map_to_export.csv')
export_df.drop('Unnamed: 0', axis = 1, inplace = True)
export_df.set_index('field_1', inplace = True)
export_df

,row,column,lat_min,lat_max,lon_min,lon_max,nature,entartainment,transports,art,sport,tourism,security,accessibility,geometry
field_1,,,,,,,,,,,,,,,
R1C2,1.0,2.0,45.000004,45.005004,11.500001,11.5075,-0.357225,-0.147138,-0.424027,-0.287166,-0.236920,-0.202676,-0.150794,-0.129103,"POLYGON ((11.5075004965 45.005003717259264, 11..."
R1C3,1.0,3.0,45.000004,45.005004,11.507500,11.5150,-0.357225,-0.147138,-0.388801,-0.287166,-0.236920,-0.202676,-0.150794,-0.129103,"POLYGON ((11.515000493 45.005003717259264, 11...."
R1C5,1.0,5.0,45.000004,45.005004,11.522500,11.5300,-0.357225,-0.147138,-0.424027,-0.287166,-0.236920,-0.202676,-0.150794,-0.129103,"POLYGON ((11.530000486 45.005003717259264, 11...."
R1C6,1.0,6.0,45.000004,45.005004,11.530000,11.5375,-0.357225,-0.147138,-0.424027,-0.287166,-0.236920,-0.202676,-0.150794,-0.129103,"POLYGON ((11.5375004825 45.005003717259264, 11..."
R1C7,1.0,7.0,45.000004,45.005004,11.537500,11.5450,-0.357225,-0.147138,-0.388801,-0.287166,-0.236920,-0.202676,-0.150794,-0.129103,"POLYGON ((11.545000479 45.005003717259264, 11...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
R200C196,200.0,196.0,45.994998,45.999998,12.955000,12.9625,-0.224525,0.085889,-0.283122,-0.287166,-0.236920,-0.202676,-0.150794,0.367314,"POLYGON ((12.9624998175 45.999997526527096, 12..."
R200C197,200.0,197.0,45.994998,45.999998,12.962500,12.9700,-0.180292,-0.147138,-0.071764,0.993911,1.689969,-0.202676,-0.150794,-0.129103,"POLYGON ((12.969999814 45.999997526527096, 12...."
R200C198,200.0,198.0,45.994998,45.999998,12.970000,12.9775,-0.357225,-0.147138,-0.424027,-0.287166,-0.236920,-0.202676,-0.150794,-0.129103,"POLYGON ((12.9774998105 45.999997526527096, 12..."
R200C199,200.0,199.0,45.994998,45.999998,12.977500,12.9850,-0.357225,-0.147138,-0.424027,-0.287166,-0.236920,-0.202676,-0.150794,-0.129103,"POLYGON ((12.984999807 45.999997526527096, 12...."
R200C200,200.0,200.0,45.994998,45.999998,12.985000,12.9925,-0.312992,-0.147138,-0.424027,-0.287166,-0.236920,-0.202676,-0.150794,-0.129103,"POLYGON ((12.9924998035 45.999997526527096, 12..."

In [44]:
export_df['predicted_tourism'] = predictions_concat.prediction_label

In [45]:
export_df

,row,column,lat_min,lat_max,lon_min,lon_max,nature,entartainment,transports,art,sport,tourism,security,accessibility,geometry,predicted_tourism
field_1,,,,,,,,,,,,,,,,
R1C2,1.0,2.0,45.000004,45.005004,11.500001,11.5075,-0.357225,-0.147138,-0.424027,-0.287166,-0.236920,-0.202676,-0.150794,-0.129103,"POLYGON ((11.5075004965 45.005003717259264, 11...",0.00
R1C3,1.0,3.0,45.000004,45.005004,11.507500,11.5150,-0.357225,-0.147138,-0.388801,-0.287166,-0.236920,-0.202676,-0.150794,-0.129103,"POLYGON ((11.515000493 45.005003717259264, 11....",0.04
R1C5,1.0,5.0,45.000004,45.005004,11.522500,11.5300,-0.357225,-0.147138,-0.424027,-0.287166,-0.236920,-0.202676,-0.150794,-0.129103,"POLYGON ((11.530000486 45.005003717259264, 11....",0.00
R1C6,1.0,6.0,45.000004,45.005004,11.530000,11.5375,-0.357225,-0.147138,-0.424027,-0.287166,-0.236920,-0.202676,-0.150794,-0.129103,"POLYGON ((11.5375004825 45.005003717259264, 11...",0.00
R1C7,1.0,7.0,45.000004,45.005004,11.537500,11.5450,-0.357225,-0.147138,-0.388801,-0.287166,-0.236920,-0.202676,-0.150794,-0.129103,"POLYGON ((11.545000479 45.005003717259264, 11....",0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
R200C196,200.0,196.0,45.994998,45.999998,12.955000,12.9625,-0.224525,0.085889,-0.283122,-0.287166,-0.236920,-0.202676,-0.150794,0.367314,"POLYGON ((12.9624998175 45.999997526527096, 12...",0.43
R200C197,200.0,197.0,45.994998,45.999998,12.962500,12.9700,-0.180292,-0.147138,-0.071764,0.993911,1.689969,-0.202676,-0.150794,-0.129103,"POLYGON ((12.969999814 45.999997526527096, 12....",0.49
R200C198,200.0,198.0,45.994998,45.999998,12.970000,12.9775,-0.357225,-0.147138,-0.424027,-0.287166,-0.236920,-0.202676,-0.150794,-0.129103,"POLYGON ((12.9774998105 45.999997526527096, 12...",0.00
R200C199,200.0,199.0,45.994998,45.999998,12.977500,12.9850,-0.357225,-0.147138,-0.424027,-0.287166,-0.236920,-0.202676,-0.150794,-0.129103,"POLYGON ((12.984999807 45.999997526527096, 12....",0.00
R200C200,200.0,200.0,45.994998,45.999998,12.985000,12.9925,-0.312992,-0.147138,-0.424027,-0.287166,-0.236920,-0.202676,-0.150794,-0.129103,"POLYGON ((12.9924998035 45.999997526527096, 12...",0.00

In [46]:
export_df.to_csv('7.final_prediction.csv')